# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PSwVPjizgbEIu_oSC9Bc53G52EFqbgf5
"""

pip install groq

!pip install gradio

from google.colab import userdata
api=userdata.get('helpAPI')

import os
from groq import Groq
import gradio as gr

# Set up the Groq client
api_key = api  # Replace with your actual API key
client = Groq(api_key=api_key)

# Function to send a query to the AI model
def chat_with_groq(user_input):
    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {"role": "user", "content": user_input}
            ],
            model="llama3-8b-8192",  # Ensure this is the correct model name
        )
        # Return the AI's response
        return chat_completion.choices[0].message.content
    except Exception as e:
        return f"Error: {e}"

# Set up Gradio Interface with labeled inputs and outputs
interface = gr.Interface(
    fn=chat_with_groq,  # Function to handle user input
    inputs=gr.Textbox(label="Your Question"),      # Input text box with a label
    outputs=gr.Textbox(label="Dr.Khan's Assistant Response"),    # Output text box with a label
    title="Dr.Khan's Assistant",
    description="Ask any question!"
)

# Launch the Gradio app
interface.launch()